### ISSUE TITLE
AdobeMobileSDK 4.7.0 missing from the Cocoapods specs repo

### ISSUE THREAD

**Issue by Eddpt** [Adobe-Marketing-Cloud/mobile-services#104]
The latest iOS SDK (version 4.7.0), released 5 days ago, is missing from Cocoapods specs repo.

Running `pod search AdobeMobileSDK` comes back with `AdobeMobileSDK (4.6.1)` as the latest available version. 

For a guide on how to update an existing Pod please look at:

[How do I update an existing Pod?](https://guides.cocoapods.org/making/specs-and-specs-repo.html)

```
Create your Podspec as described above.
Run pod spec lint to check for errors.
Submit your Podspec to Trunk with pod trunk push NAME.podspec
```

**Comment by shalehaha** [comment]
Fixed. Thanks @Eddpt  for your feedback.

**Comment by Eddpt** [comment]
Still not seeing 4.7.0 coming through either by doing `pod search AdobeMobileSDK` or by looking directly in the Cocoapods Specs repo (see [here](https://github.com/CocoaPods/Specs/tree/3594ff2908bea9f0d59bfd30baa28b67ada025f3/Specs/AdobeMobileSDK)).

Does it take a while to be pushed up to the trunk?
